default: direct

# 去广告
domain(geosite:category-ads-all) -> block

domain(geosite: gfw) -> proxy

# 国外域名即使有中国IP也要优先代理
domain(geosite:geolocation-!cn)->proxy


default: proxy

# 特定域名直连
domain(domain: gitweb.gentoo.org, domain: zedhugh.fun, domain: www.gnu.org)->direct
domain(geosite:codeberg) -> direct

domain(domain: linuxeden.com) -> proxy

# 去广告
domain(geosite:category-ads-all) -> block

# 国外域名即使有中国IP也要优先代理
domain(geosite:geolocation-!cn)->proxy

# 学术网站
domain(geosite:google-scholar)->proxy
domain(geosite:category-scholar-!cn, geosite:category-scholar-cn)->direct

# 国内直连
domain(geosite:cn) -> direct
ip(geoip:cn) -> direct

# 局域网直连
ip(geoip:private) -> direct
