# Maximum cache size to maintain
max_size = 50.0G

# Allow others to run 'ebuild' and share the cache.
umask = 002

compiler_check = %compiler% -dumpversion

cache_dir = /var/cache/ccache
# chown distcc:portage /var/cache/ccache
# chmod 2775 /var/cache/ccache